# Generated by Django 3.0.7 on 2021-01-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210110_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
