# Generated by Django 3.0.7 on 2021-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20210111_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True, verbose_name='цена'),
        ),
    ]
