# Generated by Django 3.0.7 on 2021-01-12 16:26

from django.db import migrations



def put_order_price(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    Product = apps.get_model('foodcartapp', 'Product')
    for order_product in OrderProduct.objects.all().select_related('product'):
        if order_product.price is None:
            price = Product.objects.get(id=order_product.product_id).price
            order_product.price = price
            order_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20210112_1600'),
    ]

    operations = [migrations.RunPython(put_order_price)
    ]
