# Generated by Django 3.0.7 on 2021-01-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20210115_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
